### ISSUE TITLE
picture support for retina

### ISSUE THREAD

**Issue by aolundin** [Softhouse/xyz#109]
Need to duplicate every picture uploaded. Two versions: double size with ending @2x and normal smaller size.

**Comment by phlogios** [comment]
Clarification: the @2x "double size" file is the original source resolution of the image, and the non-@2x file is a down-scaled version with half the resolution of the original. RetinaJS will show the down-scaled image on low-DPI displays, and the original image on newer devices with high DPI. This way, no information is lost on high quality displays.
