### ISSUE TITLE
Angular + Express

### ISSUE THREAD

**Issue by aolundin** [Softhouse/xyz#51]
Set up the skeleton for Angular and Express

**Comment by pawelniemiec** [comment]
Kan ni ta mig bort från den här listan varsågod?

Mvh
/Pawel

2015-06-12 12:53 GMT+02:00 alundin94 notifications@github.com:

**Comment by Tobbe** [comment]
@pawelniemiec No, I don't think we can. It's up to your settings what emails you get.
